---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through ZHA.

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_styrbar_color.yaml

  name: ZHA - IKEA TRADFRI - STYRBAR - Color LOOP Lights

  description: >-
    This automation simulates the use of the IKEA TRADFRI STYRBAR remote control
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: Remote Control N2

    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          filter:
            - domain: light

    speed:
      name: Speed
      description: The speed in which to update the light when the button is held.
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: milliseconds
          mode: slider
      default: 500

mode: restart
max_exceeded: silent

variables:
  var_light: !input light
  var_speed: !input speed

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
          - condition: state
            entity_id: !input light
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness: 176
              color_temp_kelvin: 2400
              transition: "{{ (var_speed / 1000)|int }}"
              effect: none

      # Long-Press on the right button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "hold" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3328,0] }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              effect: colorloop
      # Long-Press RELEASE on the right button.
      - conditions:
          # - condition: template
          #   value_template: '{{ trigger.event.data.command == "release" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3328,0] }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light

    # Any other event will cancel the repeat loops.
    default: []
